version: '3.6'
networks:
  dental:
services:
  postgres:
    image: docker.io/postgres:14
    networks:
    - dental
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dental
  app:
    image: 'app:latest'
    links:
    - "postgres:postgres"
    networks:
    - dental
    ports:
    - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dental
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespassword
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create
      - spring.jpa.hibernate.ddl-auto=create
      - hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
volumes:
  pg_data:  
